name: CI/CD for BB84 Simulator

on:
  push:
    branches:
      - main
      - feature-error-correction
  pull_request:
    branches:
      - main
      - feature-error-correction

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install numpy

      - name: Run tests
        run: python -m unittest test_bb84.py

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:

      - name: Checkout code
        uses: actions/checkout@v4
     
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install numpy

      - name: Simulate deploy
        run: |
          echo "Deploying BB84 Simulator..."
          python bb84.py > deploy_output.txt
          echo "Deploy completed successfully!"

      - name: Upload deploy output
        uses: actions/upload-artifact@v4
        with:
          name: deploy-output
          path: deploy_output.txt
