name: Notify Teams
on:
  push: 
  pull_request:
    branches: [main]
    types: [closed] 
jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Notify Teams
        run: echo "Workflow triggered by ${{ github.event_name }} - Commit or Merge"
